/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeeHomeRouteImport } from './routes/employee.home'
import { Route as EmployeeAttendanceRouteImport } from './routes/employee.attendance'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeHomeRoute = EmployeeHomeRouteImport.update({
  id: '/employee/home',
  path: '/employee/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeAttendanceRoute = EmployeeAttendanceRouteImport.update({
  id: '/employee/attendance',
  path: '/employee/attendance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/home': typeof EmployeeHomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/home': typeof EmployeeHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/home': typeof EmployeeHomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/employee/attendance'
    | '/employee/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/employee/attendance' | '/employee/home'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/employee/attendance'
    | '/employee/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  EmployeeAttendanceRoute: typeof EmployeeAttendanceRoute
  EmployeeHomeRoute: typeof EmployeeHomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/home': {
      id: '/employee/home'
      path: '/employee/home'
      fullPath: '/employee/home'
      preLoaderRoute: typeof EmployeeHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/attendance': {
      id: '/employee/attendance'
      path: '/employee/attendance'
      fullPath: '/employee/attendance'
      preLoaderRoute: typeof EmployeeAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  EmployeeAttendanceRoute: EmployeeAttendanceRoute,
  EmployeeHomeRoute: EmployeeHomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
